# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dolomiti1',
                'doc_host': 'https://anasbraj.github.io',
                'git_url': 'https://github.com/anasbraj/dolomiti1',
                'lib_path': 'dolomiti1'},
  'syms': {'dolomiti1.core': {'dolomiti1.core.foo': ('core.html#foo', 'dolomiti1/core.py')}}}
